server:
  port: 4001

spring:
  application:
    name: pig-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BigDuck/spring-cloud-config.git
    bus:
      trace:
        enabled: true
## 因为eureka 使用了密码保护所以defaultZone必须加上用户名和密码
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://wupj:757671834@localhost:1001/eureka